// src/app/layout.tsx
"use client"; // <-- AÑADIDO: Necesario porque los Providers usan hooks

// import type { Metadata } from "next"; // Puedes mantener el tipo si lo usas en otro lugar
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Navbar } from "@/components/navbar";
import { AuthProvider } from "@/components/providers/auth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ProductsProvider } from "@/context/ProductsContext";
import { ClientesProvider } from '@/context/ClientesContext'; // <-- 1. IMPORTADO
import { Header } from "@/components/header";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = { // <-- 4. COMENTADO: No se puede exportar metadata estática desde un Client Component
//     title: "Quimex",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" suppressHydrationWarning>
             <head>
                 {/* Añade aquí meta tags básicos si es necesario, o un título por defecto */}
                 <title>Quimex</title>
             </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AuthProvider>
                        {/* --- 3. ENVUELTO con ClientesProvider --- */}
                        <ClientesProvider>
                            <ProductsProvider>
                                {/* Header y Navbar ahora también están dentro de ClientesProvider */}
                                <Header />
                                <Navbar />
                                {/* {children} son tus páginas, ahora envueltas por todos los providers */}
                                {children}
                            </ProductsProvider>
                        </ClientesProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}