"""create costos_historico table

Revision ID: 29bf59f4da08
Revises: 20251005_categorias
Create Date: 2025-10-24 00:55:15.939546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bf59f4da08'
down_revision = '20251005_categorias'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costos_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costos_historico_fecha'), 'costos_historico', ['fecha'], unique=False)
    op.drop_index(op.f('nombre'), table_name='categorias_producto')
    op.drop_index(op.f('ix_categorias_producto_nombre'), table_name='categorias_producto')
    op.create_index(op.f('ix_categorias_producto_nombre'), 'categorias_producto', ['nombre'], unique=True)
    op.drop_index(op.f('ix_precios_moneda_original'), table_name='precios_especiales_cliente')
    op.drop_index(op.f('ix_precios_usar_precio_base'), table_name='precios_especiales_cliente')
    op.create_index(op.f('ix_precios_especiales_cliente_moneda_original'), 'precios_especiales_cliente', ['moneda_original'], unique=False)
    # op.drop_index(op.f('fk_ventas_cliente_id'), table_name='ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('fk_ventas_cliente_id'), 'ventas', ['cliente_id'], unique=False)
    op.drop_index(op.f('ix_precios_especiales_cliente_moneda_original'), table_name='precios_especiales_cliente')
    op.create_index(op.f('ix_precios_usar_precio_base'), 'precios_especiales_cliente', ['usar_precio_base'], unique=False)
    op.create_index(op.f('ix_precios_moneda_original'), 'precios_especiales_cliente', ['moneda_original'], unique=False)
    op.drop_index(op.f('ix_categorias_producto_nombre'), table_name='categorias_producto')
    op.create_index(op.f('ix_categorias_producto_nombre'), 'categorias_producto', ['nombre'], unique=False)
    op.create_index(op.f('nombre'), 'categorias_producto', ['nombre'], unique=True)
    op.drop_index(op.f('ix_costos_historico_fecha'), table_name='costos_historico')
    op.drop_table('costos_historico')
    # ### end Alembic commands ###
