"""Add cuenta and iibb to OrdenCompra

Revision ID: c44d04e3aa11
Revises: 
Create Date: 2025-06-25 15:10:56.025266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c44d04e3aa11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('iibb', sa.String(length=50), nullable=True))
        batch_op.drop_column('moneda')
        batch_op.drop_column('importe_cc')
        batch_op.drop_column('dif_ajuste_cambio')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('tipo_calculo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=2),
               nullable=True)
        batch_op.alter_column('ref_calculo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('margen',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_productos_ajusta_por_tc'), ['ajusta_por_tc'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_es_receta'), ['es_receta'], unique=False)

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ventas_cliente_id'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_ventas_cliente_id'), 'clientes', ['cliente_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_es_receta'))
        batch_op.drop_index(batch_op.f('ix_productos_ajusta_por_tc'))
        batch_op.alter_column('margen',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('ref_calculo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('tipo_calculo',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dif_ajuste_cambio', mysql.DECIMAL(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('importe_cc', mysql.DECIMAL(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('moneda', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True))
        batch_op.drop_column('iibb')
        batch_op.drop_column('cuenta')

    # ### end Alembic commands ###
