"""Add tipo_caja to OrdenCompraa

Revision ID: f9a57907d9be
Revises: 6dc6dcef1c3b
Create Date: 2025-06-25 16:25:57.206472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a57907d9be'
down_revision = '6dc6dcef1c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_caja', sa.String(length=50), nullable=True))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_ventas_cliente_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_ventas_cliente_id'), ['cliente_id'], unique=False)

    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_column('tipo_caja')

    # ### end Alembic commands ###
