# Nombre del workflow
name: Deploy Backend to Server

# Se activa con un push a la rama main si hay cambios en la carpeta backend/
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy and Restart Backend
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar la clave SSH
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. Sincronizar solo la carpeta backend al servidor
      - name: Sync backend files via rsync
        run: |
          rsync -avzr --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./backend/ \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/quimex_2.0/sistema_quimicos/

      # 4. Crear entorno virtual (si no existe), instalar dependencias y reiniciar servicio
      - name: Install dependencies and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Archivos sincronizados. Preparando entorno..."
            cd /root/quimex_2.0/sistema_quimicos

            # Crear venv si no existe
            if [ ! -d "venv" ]; then
              echo "⚙️ Creando entorno virtual..."
              python3 -m venv venv
            fi

            # Activar entorno
            source venv/bin/activate

            # Actualizar dependencias si existe requirements.txt
            if [ -f requirements.txt ]; then
              echo "📦 Instalando dependencias..."
              pip install --upgrade pip
              pip install --upgrade -r requirements.txt
            fi

            deactivate

            # Reiniciar servicio
            echo "🔄 Reiniciando servicio..."
            sudo systemctl restart quimex.service
            echo "✅ Backend desplegado y servicio reiniciado con éxito."
