name: Deploy Backend to Server

on:
  push:
    branches:
      - main # O la rama que uses
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          # Script mejorado con 'set -e' y depuración
          script: |
            # 1. (MEJORA) Salir inmediatamente si un comando falla
            set -e
            
            # 2. (NUEVO) Paso de depuración: listar archivos en el runner de GitHub
            echo "--- Listando archivos en el espacio de trabajo ---"
            ls -R ${{ github.workspace }}
            echo "------------------------------------------------"

            # 3. Navegar al directorio de destino en tu servidor
            cd /root/quimex_2.0/sistema_quimicos
            
            # 4. Sincronizar los archivos
            #    La ruta ${{ github.workspace }}/backend/ debería ser correcta,
            #    pero el paso anterior nos lo confirmará.
            rsync -avz --delete ${{ github.workspace }}/backend/ .
            
            # 5. Reiniciar el servicio
            echo "Archivos actualizados. Reiniciando el servicio..."
            sudo systemctl restart quimex.service
            echo "Servicio reiniciado con éxito."