# Nombre del workflow
name: Deploy Backend and Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend & Frontend
    runs-on: ubuntu-latest
    
    steps:
      # ... (los pasos de checkout, ssh key, backend rsync y backend deploy se mantienen igual) ...

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Sync backend files via rsync
        run: |
          rsync -avzr --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./backend/ \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/quimex_2.0/sistema_quimicos/

      - name: Sync frontend files via rsync
        run: |
          rsync -avzr --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./frontend/ \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/quimex_2.0/frontend/

      - name: Install backend dependencies and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Archivos backend sincronizados. Preparando entorno..."
            cd /root/quimex_2.0/sistema_quimicos

            if [ ! -d "venv" ]; then
              echo "⚙️ Creando entorno virtual..."
              python3 -m venv venv
            fi

            source venv/bin/activate

            if [ -f requirements.txt ]; then
              echo "📦 Instalando dependencias..."
              pip install --upgrade pip
              pip install --upgrade -r requirements.txt
            fi

            deactivate

            echo "🔄 Reiniciando servicio backend..."
            sudo systemctl restart quimex.service
            echo "✅ Backend desplegado y servicio reiniciado con éxito."

      # 6. Instalar dependencias y hacer build del frontend (SECCIÓN CORREGIDA)
      - name: Install frontend dependencies and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # --- INICIO DE LA CORRECCIÓN ---
            # Carga NVM y, por lo tanto, Node.js y npm en el PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # --- FIN DE LA CORRECCIÓN ---

            echo "🚀 Archivos frontend sincronizados. Preparando build..."
            cd /root/quimex_2.0/frontend

            # Comprobar la versión de node y npm para depuración
            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"

            if [ -f package.json ]; then
              echo "📦 Instalando dependencias frontend..."
              npm install
            fi

            echo "⚡ Compilando frontend..."
            npm run build

            echo "📂 Moviendo build a /var/www/quimex_frontend..."
            sudo rm -rf /var/www/quimex_frontend/*
            sudo cp -r build/* /var/www/quimex_frontend/

            echo "✅ Frontend compilado y desplegado."